version: "3"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      # 设置Host 为 localhost 进行域名访问
      - traefik.http.routers.blog.rule=Host(`blog.merlin218.top`)
      # 开启HTTPS
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=le

networks:
  default:
    external:
      name: traefik_default
